// Copyright (c) 2019 Otavio Santana and others
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

== Introduction to the Communication API

With the strategy to divide and conquer on Jakarta NoSQL, the communication API was born. It has the goal to make the communication layer easy and extensible. The extensibility is more than important, that is entirely necessary once the API must support specific feature in each database. Nonetheless, the advantage of a common API in a change to another database provider has lesser than using the specific API.

To cover the three of the four database types, this API includes three packages, one for each database.

* `jakarta.nosql.column`
* `jakarta.nosql.document`
* `jakarta.nosql.keyvalue`

IMPORTANT: The package name might change on the Jakarta EE process.

NOTE: A package for the Graph database type is not included in this API because we leverage the Graph communication API provided by link:http://tinkerpop.apache.org/[Apache TinkerPop].

So, if a database is multi-model, i.e., has support for more than one database type, it will implement an API for each database it supports. Also, each API has the TCK to prove if the database is compatible with the API. Even from different NoSQL types, it tries to use the same nomenclature:

* Configuration
* Factory
* Manager
* Entity
* Value

=== The API Structure

The communication has four projects:

* The *communication-core*: The Jakarta NoSQL API communication common to all database types.
* The *communication-key-value*: The Jakarta NoSQL communication API layer to a  key-value database.
* The *communication-column*: The Jakarta NoSQL communication API layer to a  column database.
* The *communication-document*: The Jakarta NoSQL communication API layer to a document database.

Each module works separately such that a NoSQL vendor just needs to implement the specific type. For example, a key-value provider will apply a key-value API. If a NoSQL driver already has a driver, this API can work as an adapter with the current one. For a multi-model NoSQL database, providers will implement the APIs they need.

WARNING: To the Graph communication API, there is the link:http://tinkerpop.apache.org/[Apache TinkerPop] that won’t be covered in this documentation.

=== Value

This interface represents the value that will store, that is, a wrapper to serve as a bridge between the database and the application. For example, if a database does not support a Java type, it may do the conversion with ease.

[source,java]
----
Value value = Value.of(12);
----

The `Value` interface has the methods:

* `Object get();` Returns the value as type `Object`

* `<T> T get(Class<T> clazz);` Initiates the conversion process to the required type in a safe manner. If the required type doesn't have support, it will throw an exception. However, the API allows creating custom converters.

* `<T> T get(TypeSupplier<T> typeSupplier);` Similar to the previous method, it initiates the conversion process using a structure that uses generics such as `List`, `Map`, `Stream` and `Set`.

[source,java]
----
Value value = Value.of(12);

String string = value.get(String.class);

List<Integer> list = value.get(new TypeReference<List<Integer>>() {});

Set<Long> set = value.get(new TypeReference<Set<Long>>() {});

Stream<Integer> stream = value.get(new TypeReference<Stream<Integer>>() {});

Object integer = value.get();
----

==== Create Custom Writer and Reader

As mentioned before, the `Value` interface is used to store the cost information into a database. The API already has support to the Java type such as primitive types, wrappers types, new Java 8 date/time. Furthermore, the developer can create a custom converter quickly and easily. It has two interfaces:


* `ValueWriter`: This interface represents an instance of `Value` to write in a database.
* `ValueReader`: This interface represents how the `Value` will convert to Java application. This interface will use the `<T> T get(Class<T> clazz)` and `<T> T get(TypeSupplier<T> typeSupplier)`.

Both class implementations load from the Java SE ServiceLoader resource. So for the Communication API to learn a new type, just register on ServiceLoader. Consider the following `Money` class:

[source,java]
----
import java.math.BigDecimal;
import java.util.Currency;
import java.util.Objects;

public class Money {

    private final Currency currency;

    private final BigDecimal value;

    private Money(Currency currency, BigDecimal value) {
        this.currency = currency;
        this.value = value;
    }

    public Currency getCurrency() {
        return currency;
    }

    public BigDecimal getValue() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Money money = (Money) o;
        return Objects.equals(currency, money.currency) &&
                Objects.equals(value, money.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(currency, value);
    }

    @Override
    public String toString() {
        return currency.getCurrencyCode() + ' ' + value;
    }

    public static Money of(Currency currency, BigDecimal value) {
        return new Money(currency, value);
    }

    public static Money parse(String text) {
        String[] texts = text.split(" ");
        return new Money(Currency.getInstance(texts[0]),
                BigDecimal.valueOf(Double.valueOf(texts[1])));
    }
}
----

NOTE: Just to be more didactic, the book creates a simple money representation. As everyone knows, reinventing the wheel is not a good practice. In a production environment, the Java developer should use mature Money APIs such as link:https://github.com/JavaMoney[Moneta], the reference implementation of link:https://jcp.org/en/jsr/detail?id=354[JSR 354].

The first step is to create the converter to a custom type database, the `ValueWriter`. It has two methods:

* `boolean isCompatible(Class clazz)`: Checks if the given class has support for this implementation.
* `S write(T object)`: Once the implementation supports the type, the next step converts an instance of type `T` to type `S`.

[source,java]
----
import jakarta.nosql.ValueWriter;

public class MoneyValueWriter implements ValueWriter<Money, String> {

    @Override
    public boolean isCompatible(Class clazz) {
        return Money.class.equals(clazz);
    }

    @Override
    public String write(Money money) {
        return money.toString();
    }
}
----

With the `MoneyValueWriter` created and the `Money` type will save as String, then the next step is read information to Java application. As can be seen, a `ValueReader` implementation. This interface has two methods:

* `boolean isCompatible(Class clazz)`; Check if the given class has support for this implementation.
* `<T> T read(Class<T> clazz, Object value)`; Converts to type `T` from an instace of `Object`.

[source,java]
----
import jakarta.nosql.ValueReader;

public class MoneyValueReader implements ValueReader {

    @Override
    public boolean isCompatible(Class clazz) {
        return Money.class.equals(clazz);
    }

    @Override
    public <T> T read(Class<T> clazz, Object value) {
        return (T) Money.parse(value.toString());
    }
}
----

After both implementations have been completed, the last step is to register them into two files:

* `META-INF/services/jakarta.nosql.ValueReader`
* `META-INF/services/jakarta.nosql.ValueWriter`

Each file will have the qualifier of its respective implementation:

The file `jakarta.nosql.ValueReader` will contain:

```
my.company.MoneyValueReader
```

The file `jakarta.nosql.ValueWriter` will contain:

```
my.company.MoneyValueWriter
```

[source,java]
----
Value value = Value.of("BRL 10.0");

Money money = value.get(Money.class);

List<Money> list = value.get(new TypeReference<List<Money>>() {});

Set<Money> set = value.get(new TypeReference<Set<Money>>() {});;
----

=== Element Entity

The *Element Entity* is a small piece of a body, except for the key-value structure type, once this structure is simple. For example, in the column family structure, the entity has columns, the element entity with column has a tuple where the key is the name, and the value is the information as an implementation of `Value`.

* *Document*
* *Column*

==== Document

The `Document` is a small piece of a Document entity. Each document has a tuple where the key is the document name, and the value is the information itself as `Value`.

[source,java]
----
Document document = Document.of("name", "value");

Value value = document.getValue();

String name = document.getName();
----

The document might have a nested document, that is, a sub-document.

[source,java]
----
Document subDocument = Document.of("subDocument", document);
----

The way to store information in sub-documents will also depend on the implementation of each database driver.

To access the information from `Document`, it has an alias method to `Value`. In other words, it does a conversion directly from `Document` _interface_.

[source,java]
----
Document age = Document.of("age", 29);

String ageString = age.get(String.class);

List<Integer> ages = age.get(new TypeReference<List<Integer>>() {});

Object ageObject = age.get();
----

==== Column

The Column is a small piece of the Column Family entity. Each column has a tuple where the name represents a key and the value itself as a `Value` implementation.

[source,java]
----
Column document = Column.of("name", "value");

Value value = document.getValue();

String name = document.getName();
----

With this interface, we may have a column inside of a column.

[source,java]
----
Column subColumn = Column.of("subColumn", column);
----

The way to store a sub-column will also depend on each driver's implementation as well as the information.

To access the information from `Column`, it has an alias method to `Value`. Thus, you can convert directly from a `Column` _interface_.

[source,java]
----
Column age = Column.of("age", 29);

String ageString = age.get(String.class);

List<Integer> ages = age.get(new TypeReference<List<Integer>>() {});

Object ageObject = age.get();
----

=== Entity

The Entity is the body of the information that goes to the database. Each database has an Entity:

* ColumnEntity
* DocumentEntity
* KeyValueEntity

==== ColumnFamilyEntity

The `ColumnFamilyEntity` is an entity to the Column Family database type. It is composed of one or more columns. As a result, the `Column` is a tuple of name and value.

[source,java]
----
ColumnEntity entity = ColumnEntity.of("columnFamily");

entity.add(Column.of("id", Value.of(10L)));

entity.add(Column.of("version", 0.001));

entity.add(Column.of("name", "Diana"));

entity.add(Column.of("options", Arrays.asList(1, 2, 3)));
----
[source,java]
----
List<Column> columns = entity.getColumns();

Optional<Column> id = entity.find("id");
----

==== DocumentEntity

The `DocumentEntity` is an entity to Document collection database type. It is composed of one or more documents. As a result, the `Document` is a tuple of name and value.

[source,java]
----
DocumentEntity entity = DocumentEntity.of("documentFamily");

String name = entity.getName();

entity.add(Document.of("id", Value.of(10L)));

entity.add(Document.of("version", 0.001));

entity.add(Document.of("name", "Diana"));

entity.add(Document.of("options", Arrays.asList(1, 2, 3)));
----
[source,java]
----
List<Document> documents = entity.getDocuments();
Optional<Document> id = entity.find("id");
entity.remove("options");
----

==== KeyValueEntity

The `KeyValueEntity` is the simplest structure. It has a tuple and a key-value structure. As the previous entity, it has direct access to information using alias method to `Value`.

[source,java]
----
KeyValueEntity<String> entity = KeyValueEntity.of("key", Value.of(123));

KeyValueEntity<Integer> entity2 = KeyValueEntity.of(12, "Text");

String key = entity.getKey();

Value value = entity.getValue();

Integer integer = entity.get(Integer.class);
----


=== Manager

The `Manager` is the class that pushes information to a database and retrieves it.


* *DocumentCollectionManager*
* *ColumnConfiguration*
* *BucketManager*

==== Document Manager

* *DocumentCollectionManager*: To perform synchronous operations.

===== DocumentCollectionManager

The `DocumentCollectionManager` is the class that manages the persistence on the synchronous way to document collection.

[source,java]
----
DocumentEntity entity = DocumentEntity.of("collection");

Document diana = Document.of("name", "Diana");

entity.add(diana);
----

[source,java]
----
List<DocumentEntity> entities = Collections.singletonList(entity);

DocumentCollectionManager manager = // instance;

// Insert operations
manager.insert(entity);

manager.insert(entity, Duration.ofHours(2L)); // inserts with two hours of TTL

manager.insert(entities, Duration.ofHours(2L)); // inserts with two hours of TTL

// Update operations
manager.update(entity);

manager.update(entities);
----

===== Search information on a document collection

The Document Communication API has support to retrieve information from the `DocumentQuery` class. The `DocumentQuery` has information such as sort type, document, and also the condition to retrieve information.

The condition on `DocumentQuery` is given from `DocumentCondition`, which has the status and the document. For example, the condition is to find a name equal "**Ada**".

[source,java]
----
DocumentCondition nameEqualsAda = DocumentCondition.eq(Document.of("name", “Ada”));
----

Also, the developer can use the aggregators such as **AND**, **OR**, and **NOT**.

[source,java]
----
DocumentCondition nameEqualsAda = DocumentCondition.eq(Document.of("name", "Ada"));

DocumentCondition youngerThan2Years = DocumentCondition.lt(Document.of("age", 2));

DocumentCondition condition = nameEqualsAda.and(youngerThan2Years);

DocumentCondition nameNotEqualsAda = nameEqualsAda.negate();
----

If there isn’t a condition in the query, that means the query will try to retrieve all information from the database, similar to a “`SELECT * FROM database`” in a relational database. Keep in mind that the return depends on the driver. It is important to say that not all NoSQL databases have support for this resource.

`DocumentQuery` also has a pagination feature to define where the data starts, and its limits.

[source,java]
----
DocumentCollectionManager manager = // instance;

DocumentQuery query = DocumentQueryBuilder.select()
    .from("collection")
    .where("age")
    .lt(10)
    .and("name")
    .eq("Ada")
    .orderBy("name")
    .asc()
    .limit(10)
    .skip(2)
    .build();

Stream<DocumentEntity> entities = manager.select(query);

Optional<DocumentEntity> entity = manager.singleResult(query);
----

===== Removing information from Document Collection

Similar to `DocumentQuery`, there is a class to remove information from the document database type: A `DocumentDeleteQuery` type.

It is more efficient than `DocumentQuery` because there is no pagination and sort feature as this information is unnecessary to remove information from database.

[source,java]
----
DocumentCollectionManager manager = // instance;
DocumentDeleteQuery query = DocumentQueryBuilder.delete().from("collection")
                      .where("age").gt(10).build();

manager.delete(query);
----

==== Column Manager

* *ColumnFamilyManager*: To perform synchronous operations.

===== ColumnFamilyManager

The `ColumnFamilyManager` is the class that manages the persistence on the synchronous way to a Column Family database.

[source,java]
----
ColumnEntity entity = ColumnEntity.of("columnFamily");

Column diana = Column.of("name", "Diana");

entity.add(diana);
----

[source,java]
----
List<ColumnEntity> entities = Collections.singletonList(entity);
ColumnFamilyManager manager = // instance;
----

[source,java]
----
// Insert operations
manager.insert(entity);

manager.insert(entity, Duration.ofHours(2L)); // inserts with two hours of TTL

manager.insert(entities, Duration.ofHours(2L)); // inserts with two hours of TTL

// Update operations
manager.update(entity);

manager.update(entities);
----

===== Search Information on a Column Family

The Column communication API has support to retrieve information from the `ColumnQuery` class. The `ColumnQuery` has information such as sort type, document and also the condition to retrieve information.

The condition on `ColumnQuery` is given from `ColumnCondition`, which has the status and the column. For example, the condition is to find a name equal "**Ada**".

[source,java]
----
ColumnCondition nameEqualsAda = ColumnCondition.eq(Column.of("name", “Ada”));
----

Also, the developer can use the aggregators such as **AND**, **OR**, and **NOT**.

[source,java]
----
ColumnCondition nameEqualsAda = ColumnCondition.eq(Column.of("name", "Ada"));

ColumnCondition youngerThan2Years = ColumnCondition.lt(Column.of("age", 2));

ColumnCondition condition = nameEqualsAda.and(youngerThan2Years);

ColumnCondition nameNotEqualsAda = nameEqualsAda.negate();
----

If there isn’t condition at the query, that means the query will try to retrieve all information from the database, look like a “`SELECT * FROM database`” in a relational database.  Keep in mind the return depends on from driver. It is important to say that not all NoSQL databases have support for this resource.

`ColumnQuery` also has pagination feature to define where the data starts, and its limits.

[source,java]
----
ColumnFamilyManager manager = // instance;
ColumnQuery query = ColumnQuery query = ColumnQueryBuilder.select()
    .from("collection")
    .where("age")
    .lt(10)
    .and("name")
    .eq("Ada")
    .orderBy("name")
    .asc()
    .limit(10)
    .skip(2)
    .build();
----

[source,java]
----
Stream<ColumnEntity> entities = manager.select(query);

Optional<ColumnEntity> entity = manager.singleResult(query);

----

===== Remove Information From Column Family

Such as `ColumnQuery`, there is a class to remove information from the column database type: A `ColumnDeleteQuery` type.

It is more efficient than `ColumnQuery` because there is no pagination and sort feature as this information is unnecessary to remove information from database.

[source,java]
----
ColumnFamilyManager manager = //instance;
ColumnDeleteQuery query = ColumnQueryBuilder.delete()
    .from("collection")
    .where("age")
    .gt(10)
    .build();
manager.delete(query);
----

==== BucketManager

The `BucketManager` is the class which saves the `KeyValueEntity` in a synchronous way in Key-Value database.

[source,java]
----
BucketManager bucketManager = //instance;
KeyValueEntity<String> entity = KeyValueEntity.of("key", 1201);

Set<KeyValueEntity<String>> entities = Collections.singleton(entity);

bucketManager.put("key", "value");

bucketManager.put(entity);

bucketManager.put(entities);

bucketManager.put(entities, Duration.ofHours(2)); // inserts with two hours TTL

bucketManager.put(entity, Duration.ofHours(2)); // inserts with two hours TTL
----

===== Remove and Retrieve Information From a Key-Value Database

With a simple structure, the bucket needs a key to both retrieve and delete information from the database.

[source,java]
----
Optional<Value> value = bucketManager.get("key");

Iterable<Value> values = bucketManager.get(Collections.singletonList("key"));

bucketManager.remove("key");

bucketManager.remove(Collections.singletonList("key"));
----

include::communication_query.adoc[]

=== Factory

The factory class creates the *Managers*.

* *ColumnFamilyManagerFactory*
* *BucketManagerFactory*
* *DocumentCollectionManagerFactory*


==== Column Family Manager Factory

The factory classes have the duty to create the Column Family manager.

* *ColumnFamilyManagerFactory*

[source,java]
----
ColumnFamilyManagerFactory factory = //instance;
ColumnFamilyManager manager = factory.get("database");
----

==== Document Collection Factory

The factory classes have the duty to create the document collection manager.

* *DocumentCollectionManagerFactory*

[source,java]
----
DocumentCollectionManagerFactory factory = //instance;
DocumentCollectionManager manager = factory.get("database");
----

==== Bucket Manager Factory

The factory classes have the responsibility to create the `BucketManager`.

[source,java]
----
BucketManagerFactory bucketManager = //instance;
BucketManager bucket = bucketManager.getBucketManager("bucket");
----

Beyond the BucketManager, some databases have support for particular structures represented in the Java world such as `List`, `Set`, `Queue` and `Map`.

[source,java]
----
List<String> list = bucketManager.getList("list", String.class);

Set<String> set = bucketManager.getSet("set", String.class);

Queue<String> queue = bucketManager.getQueue("queue", String.class);

Map<String, String> map = bucketManager.getMap("map", String.class, String.class);
----

These methods may return a `java.lang.UnsupportedOperationException` if the database does not support any of the structures.

=== Configuration

The configuration classes create a Manager Factory. This class has all the configuration to build the database connection.

There are a large number of diversity configuration flavors such as P2P, master/slave, thrift communication, HTTP, etc. The implementation may be different, however, but they have a method to return a Manager Factory. It is recommended that all database driver providers have a properties file to read this startup information.

==== Settings

The `Settings` interface represents the settings used in a configuration. It extends looks like a `Map<String, Object>`; for this reason, gives a key that can set any value as configuration.

[source,java]
----
Settings settings = Settings.builder()
    .put("key", "value")
    .build();
Map<String, Object> map = //instance;

Settings settings = Settings.of(map);
----

Each property unit has a tuple where the key is the name and the value is the property configuration. Each NoSQL database has its configuration properties.
Also, some standard configurations might be used on NoSQL databases:

* `jakarta.nosql.user`: to define a user in a NoSQL database
* `jakarta.nosql.password`: to define a password in a database
* `jakarta.nosql.host`: the host configuration that might have more than one with a number as a suffix, such as `jakarta.nosql.host-1=localhost` or `jakarta.nosql.host-2=host2`

WARNING: To read the property information, it will follow the same principal and priority from Eclipse MicroProfile Configuration and Configuration Spec JSR 382. Therefore, it will read from the  {@link `System#getProperties()`,`System#getenv()` and `Settings`.

==== Document Configuration

For the Document collection configuration, `DocumentConfiguration` configures and creates `DocumentCollectionManagerFactory`.

[source,java]
----
DocumentConfiguration configuration = //instance;
DocumentCollectionManagerFactory managerFactory = configuration.get();
----

==== Column Configuration

For the Column Family configuration, `ColumnConfiguration` creates and configures `ColumnFamilyManagerFactory`.

[source,java]
----
ColumnConfiguration configuration = //instance;

ColumnFamilyManagerFactory managerFactory = configuration.get();
----

==== Key Value Configuration

For the key-value configuration, there is `KeyValueConfiguration` to `BucketManagerFactory`.

[source,java]
----
KeyValueConfiguration configuration = //instance;
BucketManagerFactory managerFactory = configuration.get();
----
