// Copyright (c) 2019 Otavio Santana and others
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

====  Querying by text at Mapping API

As in communication layer, the Mapping has a query by text. Both communication and Mapping have the `query` and `prepare` methods, however, at the Mapping API, it will convert the fields and entities to native names from the Entity and Column annotations.

===== Key-Value

In the Key-value database, there is a `KeyValueTemplate` in this NoSQL storage technology. Usually, all the operations are defined by the ID. Therefore, it has a smooth query.
[source,java]
----
KeyValueTemplate template = ...;
Stream<User> users = template.query("get \"Diana\"");
template.query("remove \"Diana\"");
----


===== Column-Family

The column family has a little more complex structure; however, the search from the key is still recommended. E.g.: Both Cassandra and HBase have a secondary index, yet, neither have a guarantee about performance, and they usually recommend having a second table whose rowkey is your "secondary index" and is only being used to find the rowkey needed for the actual table. Given Person as an entity, then we would like to operate from the field ID, which is the entity from the Entity.


[source,java]
----
ColumnTemplate template = ...;
Stream<Person> result = template.query("select * from Person where id = 1");
----

TIP: The main difference to run using a template instead of in a manager instance is the template will do a mapper as *ColumnQueryMapperBuilder* does.

===== Document Collection

The document types allow more complex queries, so with more complex entities with a document type, a developer can find from different fields more easily and naturally. Also, there are NoSQL document types that support aggregations query, however, Eclipse Jakarta NoSQL does not support this yet. At the Eclipse Jakarta NoSQL API perspective, the document and column type is pretty similar, but with the document, a Java developer might do a query from a field that isn't a key and neither returns an unsupported operation exception or adds a secondary index for this. So, given the same Person entity with document NoSQL type, a developer can do more with queries, such as "person" between "age".

[source,java]
----
DocumentTemplate template = ...;
Stream<Person> result = template.query("select * from Person where age > 10");
----

TIP: The main difference to run using a template instead of in a manager instance is the template will do a mapper as *DocumentQueryMapperBuilder* does.

===== Graph

If an application needs a recommendation engine or a full detail about the relationship between two entities in your system, it requires a graph database. A graph database has the vertex and the edge. The edge is an object that holds the relationship information about the edges and has direction and properties that make it perfect for maps or human relationship. To the Graph API, Eclipse Jakarta NoSQL uses the Apache Tinkerpop. Likewise, the GraphTemplate is a wrapper to convert a Java entity to Vertex in TinkerPop.

[source,java]
----
GraphTemplate template =...;
Stream<City> cities = template.query("g.V().hasLabel('City')");
----

[source,java]
----
PreparedStatement preparedStatement = documentTemplate.prepare("select * from Person where name = @name");
preparedStatement.bind("name", "Ada");
Stream<Person> adas = preparedStatement.getResult();
//to graph just keep using gremlin
PreparedStatement prepare = graphTemplate().prepare("g.V().hasLabel(param)");
prepare.bind("param", "Person");
Stream<Person> people = preparedStatement.getResult();
----