// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

== References

=== Frameworks

Spring Data:: http://projects.spring.io/spring-data/[,windows=\_blank]
Hibernate OGM:: http://hibernate.org/ogm/[,windows=\_blank]
Eclipselink:: http://www.eclipse.org/eclipselink/[,windows=\_blank]
Jdbc-json:: https://github.com/jdbc-json/jdbc-cb[,windows=\_blank]
Simba:: http://www.simba.com/drivers/[,windows=\_blank]
Apache Tinkerpop:: http://tinkerpop.apache.org/[,windows=\_blank]
Apache Gora:: http://gora.apache.org/about.html[,windows=\_blank]

=== Databases

ArangoDB:: https://www.arangodb.com/[,windows=\_blank]
Blazegraph:: https://www.blazegraph.com/[,windows=\_blank]
Cassandra:: http://cassandra.apache.org/[,windows=\_blank]
CosmosDB:: https://docs.microsoft.com/en-us/azure/cosmos-db/introduction[,windows=\_blank]
Couchbase:: https://www.couchbase.com/[,windows=\_blank]
Elastic Search:: https://www.elastic.co/[,windows=\_blank]
Grakn:: https://grakn.ai/[,windows=\_blank]
Hazelcast:: https://hazelcast.com/[,windows=\_blank]
Hbase:: https://hbase.apache.org/[,windows=\_blank]
Infinispan:: http://infinispan.org/[,windows=\_blank]
JanusGraph IBM:: https://www.ibm.com/cloud/compose/janusgraph[,windows=\_blank]
Janusgraph:: http://janusgraph.org/[,windows=\_blank]
Linkurio:: https://linkurio.us/[,windows=\_blank]
Keylines:: https://cambridge-intelligence.com/keylines/[,windows=\_blank]
MongoDB:: https://www.mongodb.com/[,windows=\_blank]
Neo4J:: https://neo4j.com/[,windows=\_blank]
OriendDB:: https://orientdb.com/why-orientdb/[,windows=\_blank]
RavenDB:: https://ravendb.net/[,windows=\_blank]
Redis:: https://redis.io/[,windows=\_blank]
Riak:: http://basho.com/[,windows=\_blank]
Scylladb:: https://www.scylladb.com/[,windows=\_blank]
Stardog:: https://www.stardog.com/[,windows=\_blank]
TitanDB:: http://titan.thinkaurelius.com/[,windows=\_blank]
Memcached:: https://memcached.org/[,windows=\_blank]

=== Articles

Graph Databases for Beginners: ACID vs. BASE Explained:: https://neo4j.com/blog/acid-vs-base-consistency-models-explained/[,windows=\_blank]
Base: An Acid Alternative:: https://queue.acm.org/detail.cfm?id=1394128[,windows=\_blank]
Understanding the CAP Theorem:: https://dzone.com/articles/understanding-the-cap-theorem[,windows=\_blank]
Wikipedia CAP theorem:: https://en.wikipedia.org/wiki/CAP_theorem[,windows=\_blank]
List of NoSQL databases:: http://nosql-database.org/[,windows=\_blank]
Data access object Wiki:: https://en.wikipedia.org/wiki/Data_access_object[,windows=\_blank]
CAP Theorem and Distributed Database Management Systems:: https://towardsdatascience.com/cap-theorem-and-distributed-database-management-systems-5c2be977950e[,windows=\_blank]
Oracle Java EE 9 NoSQL view:: https://javaee.github.io/javaee-spec/download/JavaEE9.pdf[,windows=\_blank]

include::project_team.adoc[]