// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

== Introduction to the Mapping API

The mapping level, to put it differently, has the same goals as either the JPA or ORM. In the NoSQL world, the *OxM* then converts the entity object to a communication model.

This level is responsible to perform integration among technologies such as https://jakarta.ee/specifications/bean-validation/[Bean Validation]. The Mapping API provides annotations that make the Java developer's life easier. As a communication project, it must be extensible and configurable to keep the diversity of NoSQL databases.

include::annotations.adoc[]

=== Template Classes

The Template classes offer convenient creation, update, delete, and query operations for databases. The `Template` instance is the root implementation for all types. So, each database type will support this instance.

[source,java]
----
@Inject
Template template;

Book book = Book.builder()
        .id(id)
        .title("Java Concurrency in Practice")
        .author("Brian Goetz")
        .year(Year.of(2006))
        .edition(1)
        .build();

template.insert(book);
Optional<Book> optional = template.find(Book.class, id);
System.out.println("The result " + optional);
template.delete(Book.class, id);
----

Furthermore, in CRUD operations, Template provides two queries, a fluent-API for either select or delete entities. Thus, Template offers the capability for search and remove beyond the ID attribute.

[source,java]
----
@Inject
Template template;

List<Book> books = template.select(Book.class)
        .where("author")
        .eq("Joshua Bloch")
        .and("edition")
        .gt(3)
        .result();

template.delete(Book.class)
        .where("author")
        .eq("Joshua Bloch")
        .and("edition")
        .gt(3)
        .execute();
----

include::template_key_value.adoc[]
include::template_column.adoc[]
include::template_document.adoc[]
include::mapping_query.adoc[]
