// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

==== DocumentTemplate

This template has the responsibility to serve as a bridge between the entity model and the communication to a column family NoSQL database type.


The `DocumentTemplate` is the document template for the synchronous tasks.

[source,java]
----
@Inject
DocumentTemplate template;
...

Person person = new Person();
person.setAddress("Olympus");
person.setName("Artemis Good");
person.setPhones(Arrays.asList("55 11 94320121", "55 11 94320121"));
person.setNickname("artemis");

List<Person> people = Collections.singletonList(person);

Person personUpdated = template.insert(person);
template.insert(people);
template.insert(person, Duration.ofHours(1L));

template.update(person);
template.update(people);
----

To remove and retrieve information from document collection, there are `select` and `delete` methods.

[source,java]
----
@Entity
public class Person {

    @Id("native_id")
    private long id;

    @Column
    private String name;

    @Column
    private int age;
}
----

[source,java]
----
@Inject
private DocumentTemplate template;

public void mapper() {
List<Person> people = template.select(Person.class)
        .where("id")
        .gte(10)
        .result();

// translating: select().from("Person").where("native_id").gte(10L).build();

template.delete(Person.class)
        .where("id")
        .eq("20")
        .execute();

// translating: delete().from("Person").where("native_id").gte(10L).build();
}
----

To use a document template, just follow the CDI style and place an `@Inject` annotation on the field.

[source,java]
----
@Inject
private DocumentTemplate template;
----