// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

== Annotations

Jakarta NoSQL introduces a set of annotations designed to streamline and simplify the mapping of Java entities to NoSQL databases. These annotations provide:

* A standardized approach for defining entity classes.
* Specifying primary keys.
* Mapping entity properties to database fields.

Jakarta NoSQL has support for those nine types:

1. @Entity
2. @Column
3. @Id
4. @Convert
5. @Embeddable
6. @MappedSuperclass
7. @Inheritance
8. @DiscriminatorValue
9. @DiscriminatorColumn

=== @Entity

This annotation maps the class to Jakarta NoSQL. There is a single value attribute that specifies the column family name, the document collection name, etc. The default value is the simple name of the class. For example, given the `org.jakarta.nosql.demo.Person` class, the default name will be `Person`.

[source,java]
----
@Entity
public class Person {
}
----
In the case of name customization, it just needs to set the value of the @Entity annotation with the desired name as like below:

[source,java]
----
@Entity("ThePerson")
public class Person {
}
----

You can include one or multiple entities without requiring additional annotations like `OneToOne` or `OneToMany` in JPA when using the API. However, it's essential to remember that NoSQL databases have varying behaviors. For instance, in a Document database, these entities may be converted into a subdocument, while on a Key-value, it will be the value.

The sample below shows two entities, Person and Address, where a person has an address.

[source,java]
----
@Entity
public class Person {

    @Id
    private Long id;

    @Column
    private String name;

    @Column
    private Address address;
}

@Entity
public class Address {

    @Column
    private String street;

    @Column
    private String city;
}
----

The serialization method may differ depending on the NoSQL vendor.

[source,json]
----
{
   "_id":10,
   "name":"Ada Lovelave",
   "address":{
      "city":"São Paulo",
      "street":"Av Nove de Julho"
   }
}
----

=== @Column

This annotation defines which fields that belong to an Entity will be persisted. The field name specifies the column name by default.

[source,java]
----
@Entity
public class Person {
    @Column
    private String nickname;

    @Column
    private String name;

    @Column
    private List<String> phones;

    // ignored for Jakarta NoSQL
    private String address;
}
----

If any customization is needed, it just set the single attribute of the annotation to specify the desired name:

[source,java]
----
@Entity
public class Person {
    @Column
    private String nickname;

    @Column("personName")
    private String name;

    @Column
    private List<String> phones;

    // ignored for Jakarta NoSQL
    private String address;
}
----

=== @Id

This annotation defines which attribute is the entity's ID, or the Key in Key-Value databases. Unlike `@Column`, the default value is `_id`.

[source,java]
----
@Entity
public class User {

    @Id
    private String userName;

    @Column
    private String name;

    @Column
    private List<String> phones;
}
----

And, like `@Column`, if the ID’s name requires customization, it just set the single attribute of the annotation to specify the desired name:

[source,java]
----
@Entity
public class User {

    @Id("userId")
    private String userName;

    @Column
    private String name;

    @Column
    private List<String> phones;
}
----