// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

==== ColumnTemplate

The `ColumnTemplate` class is a type of Template that makes it easier to work with Column-Family or Wide-Column databases. These NoSQL databases store data in a table-like structure, where each column contains a particular attribute or piece of information.

The `ColumnTemplate` class is designed to help developers quickly work with NoSQL databases and manage complex data structures. It uses the `Template`, allowing flexible and customizable joint operations on the database.

The `ColumnTemplate` class offers excellent flexibility as it can be easily customized according to the needs of different vendors. It allows vendors to use it as a foundation for their NoSQL databases and add specific features or behaviors unique to their databases.

To effectively utilize the specific features of Column-Family or Wild-Column databases, developers require a flexible API that accommodates the variations in the behavior of NoSQL databases. The `ColumnTemplate` class offers this adaptability, allowing the creation of durable and high-performing applications.

[source,java]
----
@Inject
ColumnTemplate template;
...
Person person = new Person();
person.setAddress("Olympus");
person.setName("Artemis Good");
person.setPhones(Arrays.asList("55 11 94320121", "55 11 94320121"));
person.setNickname("artemis");

List<Person> people = Collections.singletonList(person);

Person personUpdated = template.insert(person);
template.insert(people);
template.insert(person, Duration.ofHours(1L));

template.update(person);
template.update(people);
----

To remove and retrieve information from the entity, there are `select` and `delete` methods.

[source,java]
----
@Entity
public class Person {

    @Id("native_id")
    private long id;

    @Column
    private String name;

    @Column
    private int age;
}
----

[source,java]
----
@Inject
ColumnTemplate template;
...
List<Person> people = template.select(Person.class)
        .where("id")
        .gte(10)
        .result();

// translating: select().from("Person").where("native_id").gte(10L).build();

template.delete(Person.class)
        .where("id")
        .eq("20")
        .execute();

// translating: delete().from("Person").where("native_id").gte(10L).build();

----