// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

==== DocumentTemplate

The `DocumentTemplate` class is a type of `Template` explicitly made for simplifying document-oriented tasks on NoSQL databases. These databases store data as documents, individual data sets that can be grouped into collections.

Developers can easily work with document-oriented NoSQL databases and streamline complex data structures using the `DocumentTemplate` class. This class is built on the `Template`, offering a flexible and extensible approach to defining common database operations.

The `DocumentTemplate` class offers excellent flexibility as it can be easily customized according to specific needs. Vendors can use it as a foundation to create support for additional features and behaviors that are unique to their NoSQL databases.

Because the behavior of document-oriented NoSQL databases can vary widely depending on the specific implementation, it is crucial to have a flexible API that allows for specialization. The `DocumentTemplate` class provides this flexibility and enables developers to build robust and efficient applications that take advantage of the unique features of document-oriented NoSQL databases.

One of the primary advantages of document-oriented NoSQL databases is their ability to handle semi-structured or unstructured data, which can be challenging to store and query in traditional relational databases. The DocumentTemplate class is designed to take advantage of this flexibility, providing a simple and intuitive way to work with documents, collections, and queries.

[source,java]
----
@Inject
DocumentTemplate template;
...

Person person = new Person();
person.setAddress("Olympus");
person.setName("Artemis Good");
person.setPhones(Arrays.asList("55 11 94320121", "55 11 94320121"));
person.setNickname("artemis");

List<Person> people = Collections.singletonList(person);

Person personUpdated = template.insert(person);
template.insert(people);
template.insert(person, Duration.ofHours(1L));

template.update(person);
template.update(people);
----

To remove and retrieve information from document collection, there are `select` and `delete` methods.

[source,java]
----
@Entity
public class Person {

    @Id("native_id")
    private long id;

    @Column
    private String name;

    @Column
    private int age;
}
----

[source,java]
----
@Inject
private DocumentTemplate template;

public void mapper() {
List<Person> people = template.select(Person.class)
        .where("id")
        .gte(10)
        .result();

// translating: select().from("Person").where("native_id").gte(10L).build();

template.delete(Person.class)
        .where("id")
        .eq("20")
        .execute();

// translating: delete().from("Person").where("native_id").gte(10L).build();
}
----