
== Entity Classes [[entity_definition]]

The notion of an _entity_ is the fundamental building block with which a data model may be constructed.
Abstractly, an entity (or _entity type_) is a schema for data.

- The schema may be as simple as a tuple of types or it might be structured, as in document data stores.
- The schema might be explicit or it might be implicit, as is commonplace in key/value stores.
- Either way, we assume that the entity is represented in Java as a class, which we call the _entity class_. footnote:[We will not consider generic programs which work with entity data via detyped representations.]

NOTE: When there's no risk of confusion, we often use the word “entity” to mean the entity class, or even an instance of the entity class.

Data represented by an entity is persistent, that is, the data itself outlives any Java process which makes use of it. Thus, it is necessary to maintain an association between instances of Java entity classes and state held in a data store.

- Each persistent instantiation of the schema is distinguishable by a unique _identifier_.
- Any persistent instantiation of the schema is representable by an instance of the entity class. In a given Java program, multiple entity class instances might represent the same persistent instance of the schema.

In Jakarta NoSQL, the concrete definition of an entity may be understood to encompass the following aspects:

1. The *entity class* itself: An entity class is simple Java object equipped with fields or accessor methods designating each property of the entity. An entity class is identified by an annotation.

2. Its *data schema*: Some data storage technologies require an explicit schema defining the structure and properties of the data the entity represents.

=== Programming Model for Entity Classes

A _programming model for entity classes_ specifies:

- a set of restrictions on the implementation of a Java class that allows it to be used as an entity class with a given Jakarta NoSQL provider, and
- a set of annotations allowing the identification of a Java class as an entity class, and further specification of the entity's schema.

Jakarta NoSQL defines its programming model for entities explicitly. It relies on annotations provided by the specification. Jakarta NoSQL's programming model allows for seamless integration with custom annotations defined by Jakarta NoSQL providers or extensions.

This approach ensures flexibility and interoperability, enabling developers to leverage Jakarta NoSQL's standardized annotations alongside provider-specific annotations for fine-tuning entity behavior and mapping. Additionally, Jakarta NoSQL facilitates integration with other Jakarta EE specifications, fostering a cohesive Java-based NoSQL application development ecosystem.

This section lays out the core requirements that an entity programming model must satisfy to be compatible with Jakarta Data and for the defining provider to be considered a fully compliant implementation of this specification.

Every entity programming model specifies an _entity-defining annotation_, `jakarta.nosql.Entity`.

Furthermore, an entity programming model must define an annotation that identifies the field or property holding the unique identifier of an entity, the `Jakarta.nosql.Id`.

Typically, an entity programming model specifies additional annotations used to make the entity schema explicit, for example, `jakarta.nosql.Id` and `jakarta.nosql.Column`. The nature of such annotations is beyond the scope of this specification.

In a given entity programming model, entity classes are always mutable, or immutable, or the model might support a mix of mutable and immutable entity classes.

- A programming model that supports immutable entity classes may require that every mutable entity class declare a constructor with no parameters and might limit this constructor's visibility.
- A programming model that supports the use of immutable entity classes--ideally represented as Java `record` types--would not typically require the existence of such a constructor.

In either case, an entity programming model might restrict the visibility of an entity class's fields and property accessors.

An entity programming model might support inheritance between entities and provide support for retrieving entities in a polymorphic fashion. This specification does not require support for inheritance.

To ensure compatibility with Jakarta NoSQL, an entity programming model must adhere to the following constructor rules:
- Constructors must be `public` or `protected` with no parameters or with parameters annotated with `Jakarta.nosql.Column` or `Jakarta.nosql.Id`.
- Annotations at the constructor will build the entity and read information from the database, while field annotations are required to write information to the database.
- If both a non-args constructor and a constructor with annotated parameters exist, the constructor with annotations will be used to create the entity.
- Constructor parameters without annotations will be ignored, utilizing a non-arg constructor instead.
- Entities should not have multiple constructors using `jakarta.nosql.Id` or `jakarta.nosql.Column` annotations.

==== Persistent Fields

A field of an entity class may or may not represent state which is persistent in the datastore.
A _persistent field_ has some corresponding representation in the data schema of the entity.


Every programming model for entity classes must support _direct field access_, that is, access to the persistent fields of an entity class without triggering any intermediating user-written code such as JavaBeans-style property accessors.

A programming model might place constraints on the visibility of persistent fields.

Jakarta NoSQL distinguishes three kinds of persistent field within entity classes.

- A _basic field_ holds a value belonging to some fundamental data type supported natively by the Jakarta NoSQL Provider. Support for the set of basic types enumerated in the next section below is mandatory for all Jakarta NoSQL providers.
- An _embedded field_ allows the inclusion of the state of a finer-grained Java class within the state of an entity. The type of an embedded field is often a user-written Java class. Support for embedded fields varies depending on the Jakarta NoSQL provider and the database type.
- An _association field_ implements an association between entity types. Support for association fields varies depending on the Jakarta NoSQL provider and the database type.

==== Basic Types [[basic_types]]

Every Jakarta NoSQL provider must support the following basic types within its programming model:

|===
| Basic Data Type | Description

| Primitive types and wrapper classes
| All Java primitive types, such as `int`, `double`, `boolean`, etc., and their corresponding wrapper types from `java.lang` (e.g., `Integer`, `Double`, `Boolean`).

| `java.lang.String`
| Represents text data.

| `LocalDate`, `LocalDateTime`, `LocalTime`, `Instant` from `java.time`
| Represent date and time-related data.

| `java.util.UUID`
| Universally Unique IDentifier for identifying entities.

| `BigInteger` and `BigDecimal` from `java.math`
| Represent large integer and decimal numbers.

| `byte[]`
| Represents binary data.

| User-defined `enum` types
| Custom enumerated types defined by user-written code.
|===

For example, the following entity class has five basic fields:

[source,java]
----
@Entity
public class Person {
    @Id
    private UUID id;
    @Column
    private String name;
    @Column
    private long ssn;
    @Column
    private LocalDate birthdate;
    @Column
    private byte[] photo;
}
----

In addition to the types listed above, an entity programming model might support additional domain-specific basic types. This extended set of basic types might include types with a nontrivial internal structure. An entity programming model might even provide mechanisms to convert between user-written types and natively-supported basic types, defined at the `AttributeConverter` interface.

NOTE: Many key-value, wide-column, and document databases feature native support for arrays or even associative arrays of these basic types.

==== Embedded Fields and Embeddable Classes [[embeddable_definition]]

An _embeddable class_ differs from an entity class in that:

- the embeddable class lacks its own persistent identity and
- the state of an instance of the embeddable class can only be stored in the database when the instance is referenced directly or indirectly by a "parent" entity class instance.

An _embedded field_ is a field whose type is an embeddable class.

Embeddable classes may have basic fields, embeddable fields, and association fields, but unlike entities, they do not have identifier fields.

Like entities, a programming model for entity classes might support mutable embeddable classes, immutable embeddable classes, or both.

Jakarta NoSQL defines an annotation identifying a user-written class as an embeddable class: `jakarta.nosql.Embeddable`.

There are two natural ways that a Jakarta NoSQL provider might store the state of an instance of an embedded class in a database:

- by _flattening_ the fields of the embeddable class into the data structure representing the parent entity or
- by _grouping_ the fields of the embedded class into a fine-grained structured type (a User-defined type,*UDT*, for example).

In a flattened representation of an embedded field, the fields of the embeddable class occur directly alongside the basic fields of the entity class in the data schema of the entity.
There is no representation of the embeddable class itself in the data schema.

To ensure compatibility with Jakarta NoSQL, an embeddable class must adhere to the following constructor rules:
- Constructors must be `public` or `protected` with no parameters or parameters annotated with `jakarta.nosql.Column` or `jakarta.nosql.Id`.
- Annotations at the constructor will build the entity and read information from the database, while field annotations are required to write information to the database.
-If both a non-args constructor and a constructor with annotated parameters exist, the constructor with annotations will be used to create the entity.
- Constructor parameters without annotations will be ignored, utilizing a non-arg constructor instead.
- Embeddable classes should not have multiple constructors using `jakarta.nosql.Id` or `jakarta.nosql.Column` annotations.

For example, consider the following Java classes:

[source,java]
----
@Embeddable
public class Address {
    @Column
    private String street;
    @Column
    private String city;
    @Column
    private String postalCode;
}

@Entity
public class Person {
    @Id
    private Long id;
    @Column
    private String name;
    @Column
    private Address address;  // embedded field
}
----

In a document, wide-column, or graph database, the JSON representation of an instance of the `Person` entity might be as follows:

[source,json]
----
{
  "id": 1,
  "name": "John Doe",
  "street": "123 Main St",
  "city": "Sampleville",
  "postalCode": "12345"
}
----


In a structured representation, the fields of the embeddable class are somehow grouped together in the data schema.

For example, the JSON representation of `Person` might be:

[source,json]
----
{
  "id": 1,
  "name": "John Doe",
  "address":
  {
    "street": "123 Main St",
    "city": "Sampleville",
    "postalCode": "12345"
  }
}
----

NOTE: Support for embeddable classes and embedded fields is not required by this specification.
However, every Jakarta NoSQL provider is strongly encouraged to provide support for embeddable classes within its entity programming model.

==== Entity Associations

An association field is a field of an entity class whose declared type is also an entity class.
Given an instance of the first entity class, its association field holds a reference to an instance of a second entity class.

For example, consider the following Java classes:

[source,java]
----
@Entity
public class Author {
    @Id
    private UUID id;
    @Column
    private String name;
    @Column
    private List<Book> books;
}

@Entity
public class Book {
    @Column
    private String title;
    @Column
    private String category;
}
----

For example, the JSON representation of `Author` might be:

[source,json]
----
{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "name": "John Smith",
  "books": [
    {
      "title": "Java Programming",
      "category": "Programming"
    },
    {
      "title": "Introduction to NoSQL",
      "category": "Database"
    }
  ]
}
----


NOTE: Support for entity associations is not required by this specification.

==== Entity Property Names

Within an entity, property names must be unique ignoring case. For simple entity properties, the field or accessor method name serves as the entity property name. In the case of embedded classes, entity property names are computed by concatenating the field or accessor method names at each level, optionally joined by a delimiter.
