// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

====  Querying by Text with the Mapping API

Jakarta NoSQL provides query by text that you can execute. Furthermore, there is the option to explore a prepared statement query. Jakarta NoSQL does not provide any query support. Thus, any vendor might have diverse queries.

===== Key-Value Database Types

[source,java]
----
KeyValueTemplate template = // instance;
Stream<User> users = template.query("get \"Diana\"");
template.query("remove \"Diana\"");
----

===== Column-Family Database Types

[source,java]
----
ColumnTemplate template = // instance;
Stream<Person> result = template.query("select * from Person where id = 1");
----

===== Document Database Types

[source,java]
----
DocumentTemplate template = // instance;
Stream<Person> result = template.query("select * from Person where age > 10");
----
