// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

== Introduction

=== One Mapping API, Multiple Databases

Jakarta NoSQL is a Java framework that streamlines the integration of Java applications with NoSQL databases.

Jakarta NoSQL defines an API for each NoSQL database type:

* Key-Value
* Column Family
* Document
* Graph

However, it uses the same annotations to map Java objects. Therefore, with just these annotations, whose names match those from the Jakarta Persistence specification, there is support for more than twenty NoSQL databases.

[source,java]
----
@Entity
public class Deity {

    @Id
    private String id;

    @Column
    private String name;

    @Column
    private String power;
 //...
}
----

Developers need to consider vendor lock-in when choosing a NoSQL database for their application. For example, if there is a need to switch out a database considerations include: the time spent on the change; the learning curve of a new database API; the code that will be lost; the persistence layer that needs to be replaced, etc. Jakarta NoSQL avoids most of these issues through the *Mapping* API.

Jakarta NoSQL also provides template classes that apply the *Template Method* design pattern to all database operations.

=== Beyond Jakarta Persistence (JPA)

The https://jakarta.ee/specifications/persistence/[Jakarta Persistence] specification is an excellent API for object-relational mapping and has established itself as a Jakarta EE standard. It would be ideal to use the same API for both SQL and NoSQL, but there are behaviors in NoSQL that SQL does not cover, such as time-to-live and asynchronous operations. Jakarta Persistence was simply not designed to handle those features.

[source,java,subs="quotes"]
----
ColumnTemplate template = // instance; a template to document NoSQL operations
Deity diana = Deity.builder()
        .withId("diana")
        .withName("Diana")
        .withPower("hunt")
        .build();

*Duration ttl = Duration.ofSeconds(1);*
template.insert(diana, *ttl*);
----

=== A Fluent API

Jakarta NoSQL is a fluent API for Java developers to more easily create queries that either retrieve or delete information in a `Document` database type. For example:

[source,java]
----
DocumentTemplate template = // instance; a template to document NoSQL operations
Deity diana = Deity.builder()
        .withId("diana")
        .withName("Diana")
        .withPower("hunt")
        .build();

template.insert(diana);// insert an entity

List<Deity> deities = template.select(Deity.class)
        .where("name")
        .eq("Diana").result(); // SELECT Deity WHERE name equals “Diana”

template.delete(Deity.class).where("name")
        .eq("Diana").execute();
----

=== Let's Not Reinvent the Wheel: Graph Database Type

The Communication layer defines three new APIs for NoSQL database types: Key-Value, Column Family and Document. It does not provide the new Graph API because a very good one already exists. https://tinkerpop.apache.org/[Apache TinkerPop] is a graph computing framework for both graph databases (OLTP) and graph analytic systems (OLAP). Using Apache TinkerPop as the Communication API for Graph databases, the Mapping API has a tight integration with it.

=== Particular Behavior Matters in NoSQL Databases

Even within the same type, each NoSQL database has a unique feature that may be a considerable factor when choosing one database over another. This "feature" might make it easier to develop, make it more scaleable or consistent from a configuration standpoint, have the desired consistency level or search engine, etc. Some examples include: Cassandra and its Cassandra Query Language and consistency level; OrientDB with live queries; ArangoDB and its Arango Query Language; Couchbase with N1QL; etc. Each NoSQL database has a specific behavior and this behavior matters, so Jakarta NoSQL was designed to be extensible enough to capture these substantially different feature elements.

=== Key Features

* Simple APIs that support all well-known NoSQL storage types: Key-Value, Column Family, Document and Graph databases
* Use of Convention Over Configuration
* Easy-to-implement API Specification and Technology Compatibility Kit (TCK) for NoSQL Vendors
* The APIs focus is on simplicity and ease-of-use. Developers should only have to know a minimal set of artifacts to work with Jakarta NoSQL. The API is built on Java 8 features like Lambdas and Streams, and therefore fits perfectly with the functional features of Java 8+.

include::project_team.adoc[]
